version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    networks:
      - test
    volumes:
      - db:/var/lib/mysql
  SopraHRWork:
    depends_on:
      - mysqldb
    image: task:latest
    ports:
      - "8085:8082"
    networks:
      - test
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/project_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : null

          }'
      stdin_open: true
      tty: true

networks:
  test:

volumes:
  db: {}
